/**
 * Erstinhalte des Wissensbereichs, übernommen aus dem Rehabilitationstagebuch
 * (Alexander Koetter). Werden als ENTWURF angelegt (ADR 0009): Vor der Veröffentlichung
 * prüft der Autor die Formulierungen, insbesondere die Nährstoff-Tabellen gegen die
 * Health-Claims-Verordnung. Stellen, die dafür bekannt problematisch sind, tragen
 * einen Hinweis-Callout.
 */
import { b, baustein, doc, h2, h3, i, info, ol, p, summary, table, ul, warning } from "../src/lib/content/build";
import type { Doc } from "../src/lib/content/types";
import type { ContentCategory } from "../src/lib/labels";

export type SeedArticle = { slug: string; title: string; category: ContentCategory; position: number; body: Doc };

export const seedContent: SeedArticle[] = [
  {
    slug: "einleitung",
    title: "Drei Säulen der Rehabilitation",
    category: "einfuehrung",
    position: 0,
    body: doc(
      p("Eine erfolgreiche Rehabilitation ist kein Zufallsprodukt, sondern das Ergebnis einer klaren Struktur. Wer nach einer Verletzung oder Operation wieder die volle Leistungsfähigkeit erreichen und sicher zum Sport zurückkehren möchte (Return to Sport), profitiert von einem strukturierten Rehabilitationsplan, der Fortschritte sichtbar macht, Rückschläge früh erkennt und die Motivation über Wochen und Monate aufrechterhält."),
      p("Viele Menschen setzen Rehabilitation mit reinem Training gleich. Tatsächlich beruht eine wirksame Regeneration auf drei gleichwertigen Säulen: ", b("Bewegung, Ernährung und Schlaf"), ". Nur wenn alle drei Bereiche berücksichtigt werden, kann sich der Körper optimal anpassen, Gewebe reparieren und langfristig belastbar werden. Training setzt den notwendigen Reiz, Ernährung liefert die Bausteine für Reparatur und Wachstum, und Schlaf ist die Phase, in der die eigentliche Regeneration stattfindet."),
      p("Dieses Portal soll Sie dabei unterstützen, alle drei Säulen im Blick zu behalten. Es bietet Hintergrundwissen, konkrete Empfehlungen Ihrer Praxis und die Möglichkeit, Training, Supplementeinnahme und Fortschritte zu dokumentieren. So wird aus einzelnen Trainingseinheiten ein durchdachter, nachvollziehbarer Prozess."),
    ),
  },
  {
    slug: "schlaf",
    title: "Säule des Schlafes",
    category: "schlaf",
    position: 0,
    body: doc(
      p("Schlaf ist die wichtigste Regenerationsphase für Körper und Psyche. Während des Schlafs werden Gewebe repariert, Wachstumshormone ausgeschüttet, das Immunsystem gestärkt und Erlebtes im Gehirn verarbeitet und abgespeichert. Schlafmangel verlangsamt Heilungsprozesse, erhöht das Verletzungsrisiko und wirkt sich negativ auf Konzentration, Stimmung und Schmerzempfinden aus."),
      h3("Die Schlafphasen"),
      ul(
        [b("Einschlafphase: "), "Der Körper entspannt sich, Muskeltonus und Herzfrequenz sinken."],
        [b("Leichtschlaf: "), "Der größte Teil der Nacht; erste Erholung von Muskulatur und Nervensystem."],
        [b("Tiefschlaf: "), "Wichtigste Phase für körperliche Regeneration: Gewebereparatur, Muskelaufbau und Ausschüttung von Wachstumshormonen finden hier statt."],
        [b("REM-Schlaf: "), "Zuständig für psychische Erholung, Gedächtniskonsolidierung und Verarbeitung von Emotionen."],
      ),
      h3("Die HRV-Rate"),
      p("Die Herzratenvariabilität (HRV) beschreibt die Schwankung der Zeitabstände zwischen aufeinanderfolgenden Herzschlägen. Eine hohe HRV deutet auf ein gut erholtes Nervensystem und eine hohe Regenerationsfähigkeit hin, während eine niedrige HRV auf Stress, Übertraining oder unzureichende Erholung hinweisen kann. Die tägliche Beobachtung der HRV hilft dabei, die Trainingsbelastung individuell zu steuern und Übertraining frühzeitig zu erkennen."),
      h3("Methoden zur Schlafverbesserung"),
      ul("Ca. 8 Stunden Schlaf pro Nacht einplanen.", "Kühle Raumtemperatur beim Schlafen (ca. 16–18 °C).", "Blaulicht (Bildschirme) am Abend vermeiden.", "Tagsüber viel natürliches Licht, besonders am Morgen.", "Atemübungen zur Beruhigung des Nervensystems vor dem Einschlafen."),
      h3("Atemübungen"),
      p(b("4-7-8: "), "4 Sekunden durch die Nase einatmen, 7 Sekunden die Luft anhalten, 8 Sekunden langsam durch den Mund ausatmen. Diesen Zyklus 4-mal wiederholen. Diese Technik beruhigt das Nervensystem und erleichtert das Einschlafen."),
      p(b("Box Breathing (4-4-4-4): "), "4 Sekunden einatmen, 4 Sekunden die Luft anhalten, 4 Sekunden ausatmen, 4 Sekunden Pause halten. Diesen Zyklus mehrfach wiederholen. Die gleichmäßige Struktur hilft, Stresshormone zu senken und den Geist zu beruhigen."),
      baustein("atem"),
      summary("Ausreichend Schlaf (ca. 8 Stunden), eine kühle und dunkle Schlafumgebung sowie Atemübungen vor dem Einschlafen unterstützen die nächtliche Regeneration. Die tägliche Beobachtung der HRV hilft dabei, Übertraining frühzeitig zu erkennen und die Trainingsbelastung passend zu steuern."),
    ),
  },
  {
    slug: "ernaehrung",
    title: "Säule der Ernährung",
    category: "ernaehrung",
    position: 0,
    body: doc(
      p("Makronährstoffe (Proteine, Kohlenhydrate und Fette) liefern dem Körper Energie und Baumaterial in großen Mengen. Mikronährstoffe (Vitamine, Mineralstoffe und Spurenelemente) werden nur in kleinen Mengen benötigt, sind aber essenziell für Stoffwechselprozesse, Immunfunktion und Geweberegeneration."),
      p("Proteine sind der wichtigste Baustein für die Reparatur von Muskel-, Sehnen- und Bindegewebe und sollten in einer Rehabilitationsphase ausreichend und regelmäßig über den Tag verteilt aufgenommen werden. Kohlenhydrate liefern die notwendige Energie für Training und Alltag und unterstützen die Auffüllung der Glykogenspeicher, was die Trainingsqualität und Regeneration verbessert."),
      h3("Ruheumsatz (Grundumsatz)"),
      p("Der Ruheumsatz beschreibt die Energiemenge, die der Körper in vollständiger Ruhe benötigt, um alle lebensnotwendigen Funktionen aufrechtzuerhalten, etwa Atmung, Herzschlag, Zellerneuerung und Temperaturregulation. Er bildet die Grundlage für die Berechnung des gesamten Energiebedarfs."),
      p("Gerade in der Rehabilitation ist diese Kenntnis wichtig: Nur wenn ausreichend Energie und Protein bereitgestellt werden, kann der Körper geschädigtes Gewebe reparieren, Muskulatur erhalten und den durch Heilungsprozesse erhöhten Energiebedarf decken. Eine zu geringe Kalorienzufuhr verstärkt den Muskelabbau, während eine deutliche Überversorgung unnötige Fettzunahme begünstigt."),
      p(i("Formel nach Mifflin-St-Jeor: "), "Mann: 10 × Gewicht (kg) + 6,25 × Größe (cm) − 5 × Alter (Jahre) + 5. Frau: 10 × Gewicht (kg) + 6,25 × Größe (cm) − 5 × Alter (Jahre) − 161."),
      baustein("ruheumsatz"),
      p(i("Quellen: Balci et al., 2021; Harrison & Benedict, 1918; Jesus et al., 2020; Mifflin & St Jeor, 1990.")),
      summary("Ausreichend Protein (regelmäßig über den Tag verteilt), ein an den Ruheumsatz angepasstes Energieniveau sowie die gezielte, dokumentierte Einnahme der mit Ihrer Praxis abgestimmten Supplemente bilden gemeinsam die Grundlage für Geweberegeneration und Muskelerhalt während der gesamten Reha."),
    ),
  },
  {
    slug: "mikronaehrstoffe",
    title: "Mikronährstoffe und Aminosäuren",
    category: "ernaehrung",
    position: 1,
    body: doc(
      warning("Redaktionshinweis (vor Veröffentlichung entfernen): Die Wirkaussagen in diesen Tabellen stammen aus dem Tagebuch und müssen gegen die Liste zugelassener Health Claims (EU 1924/2006) geprüft werden. Aussagen wie „unterstützt die Wundheilung“ oder „wirkt entzündungshemmend“ sind in dieser Form nicht zugelassen."),
      p("Die folgende Tabelle gibt einen Überblick über wichtige Vitamine, Mineralstoffe und Spurenelemente sowie ihre Funktion für Geweberegeneration, Immunsystem und Energiestoffwechsel während der Rehabilitation."),
      table(["Nährstoff", "Wirkung / Funktion im Körper"], [
        ["Vitamin A", "Unterstützt Zellwachstum, Immunfunktion und die Regeneration von Haut- und Schleimhautgewebe."],
        ["Vitamin B", "Wichtig für Energiestoffwechsel, Nervenfunktion und Bildung roter Blutkörperchen (B-Komplex)."],
        ["Vitamin C", "Fördert die Kollagenbildung, unterstützt die Wundheilung und wirkt antioxidativ."],
        ["Vitamin D", "Reguliert den Kalziumhaushalt, unterstützt Knochenstabilität, Muskelfunktion und Immunsystem."],
        ["Selen", "Antioxidatives Spurenelement, unterstützt Immunsystem und Schilddrüsenfunktion."],
        ["Eisen", "Notwendig für den Sauerstofftransport im Blut und die Energiebereitstellung der Muskulatur."],
        ["Omega 3", "Wirkt entzündungshemmend, unterstützt Hirn- und Herz-Kreislauf-Gesundheit."],
        ["Omega 6", "Wichtige Fettsäure für Zellmembranen, in ausgewogenem Verhältnis zu Omega 3 relevant."],
        ["Creatin", "Unterstützt die schnelle Energiebereitstellung im Muskel und fördert Kraft- und Muskelaufbau."],
        ["Glycin", "Aminosäure mit Bedeutung für Kollagenbildung, Bindegewebe und erholsamen Schlaf."],
        ["Antioxidantien", "Neutralisieren freie Radikale und reduzieren oxidativen Stress nach Belastung."],
        ["Calcium", "Wichtigster Baustein für Knochen und Zähne, unterstützt Muskelkontraktion, Blutgerinnung und Reizübertragung an Nervenzellen."],
        ["Magnesiumcitrat", "Gut bioverfügbare Form, unterstützt Muskelentspannung und Energiestoffwechsel, bei höherer Dosierung leicht abführende Wirkung."],
        ["Magnesiumbisglycinat", "An Glycin gebunden, magenschonend, unterstützt Muskelregeneration und erholsamen Schlaf."],
        ["Magnesiumchlorid", "Gut bioverfügbare Form, unterstützt Muskel- und Nervenfunktion."],
        ["Magnesiummalat", "Kombination mit Apfelsäure, unterstützt Energiebereitstellung und Linderung von Muskelverspannungen."],
      ]),
      h3("Essentielle Aminosäuren und BCAA"),
      p("Essentielle Aminosäuren kann der Körper nicht selbst herstellen und muss sie über die Nahrung aufnehmen. Die folgende Tabelle zeigt ihre jeweilige Funktion für Muskelaufbau, Gewebereparatur und Regeneration."),
      table(["Nährstoff", "Wirkung / Funktion im Körper"], [
        ["Leucin", "Zentraler Reiz für die Muskelproteinbiosynthese (auch BCAA)."],
        ["Isoleucin", "Unterstützt Energiebereitstellung und Muskelregeneration (auch BCAA)."],
        ["Valin", "Fördert Muskelaufbau und -erhalt, Energielieferant bei Belastung (auch BCAA)."],
        ["Lysin", "Wichtig für Kollagenbildung, Gewebereparatur und Immunfunktion."],
        ["Methionin", "Beteiligt an Stoffwechsel- und Entgiftungsprozessen sowie Gewebeaufbau."],
        ["Threonin", "Baustein für Kollagen und Elastin, unterstützt Bindegewebe."],
        ["Phenylalanin", "Vorstufe wichtiger Botenstoffe, relevant für Nervensystem."],
        ["Tryptophan", "Vorstufe von Serotonin und Melatonin, relevant für Stimmung und Schlaf."],
        ["Histidin", "Unterstützt Gewebewachstum und -reparatur, Vorstufe von Histamin."],
      ]),
    ),
  },
  {
    slug: "ernaehrung-operation",
    title: "Ernährungsleitfaden bei einer Operation",
    category: "ernaehrung",
    position: 2,
    body: doc(
      p("Stoffwechsel und Ernährung nach einer Operation: Dieses Kapitel ergänzt die Säule der Ernährung um die besonderen Anforderungen rund um einen operativen Eingriff."),
      h3("Was passiert biologisch nach einer Operation?"),
      p("Jede Operation, unabhängig von ihrer Größe, löst im Körper eine komplexe Stressreaktion aus. Der Körper versetzt sich in einen hypermetabolisch-katabolen Zustand: Er verbraucht sehr viel Energie und baut gleichzeitig eigenes Gewebe (vor allem Muskel) ab, um diese Energie zu gewinnen."),
      h3("1. Hormonelle Stressantwort"),
      p("Direkt nach dem Eingriff schüttet der Körper große Mengen an Stresshormonen aus:"),
      table(["Hormon / Botenstoff", "Wirkung"], [
        ["Cortisol (Stresshormon)", "Hemmt Muskelproteinsynthese, fördert Muskelabbau"],
        ["Glucagon", "Stimuliert Glukoseproduktion in der Leber"],
        ["Proinflammatorische Zytokine", "Entzündungsreaktion, erhöhter Energiebedarf"],
      ]),
      p("Diese hormonelle Reaktion kann je nach Schwere der Operation wenige Stunden bis zu 2–4 Wochen anhalten."),
      h3("2. Post-operative Insulinresistenz"),
      p("Unter normalen Umständen transportiert Insulin Blutzucker (Glukose) aus dem Blut in die Körperzellen. Nach einer Operation reagieren die Zellen schlechter auf Insulin, sie „hören nicht mehr richtig hin“. Einfach erklärt: Insulin klopft an die Zellentür, aber die Zelle öffnet nicht. Der Blutzucker bleibt im Blut und steigt an (Hyperglykämie), obwohl genug Insulin vorhanden ist."),
      p(b("Folgen der Insulinresistenz:")),
      ul("Blutzucker steigt stark an (Hyperglykämie)", "Die Aufnahme und Verbrennung von Glukose ist gestört", "Die Leber produziert weiter Glukose aus Aminosäuren (Muskelprotein!), Laktat und Glycerin (Gluconeogenese)", "Das Immunsystem wird geschwächt, höheres Infektions- und Komplikationsrisiko"),
      info("Auch gesunde Menschen entwickeln diese Insulinresistenz nach Operationen. Bei Diabetikern oder Personen mit bereits erhöhtem Blutzucker ist sie deutlich ausgeprägter und gefährlicher."),
      h3("3. Muskelabbau (Katabolismus)"),
      p("Der erhöhte Energiebedarf und die Insulinresistenz führen dazu, dass der Körper sich aus dem Muskeleiweiß bedient: Aminosäuren werden aus der Skelettmuskulatur freigesetzt und für drei Zwecke verwendet:"),
      ol("Gluconeogenese: Herstellung von Blutzucker aus Aminosäuren", "Wundheilung: Bereitstellung von Baustoffmolekülen für geschädigtes Gewebe", "Immunfunktion: Unterstützung des Abwehrsystems"),
      p("Dieser Muskelabbau beginnt bereits innerhalb von 48 Stunden nach Inaktivität und verstärkt sich durch die OP-bedingte Immobilisierung erheblich:"),
      baustein("muskelverlust"),
      h3("Warum reichen Kohlenhydrate allein nicht aus?"),
      p("Eine rein kohlenhydratbetonte Ernährung kann die Insulinresistenz zwar um bis zu 50 % verringern, aber nicht vollständig aufheben. Außerdem:"),
      ul("Der Körper kann Glukose nach dem Eingriff nicht effizient oxidieren", "Post-operative Kohlenhydratzufuhr hat keinen relevanten Effekt auf die Insulinresistenz", "Gluconeogenese aus Aminosäuren läuft weiter, solange kein Protein zugeführt wird", "Glukose stellt keine Aminosäuren für Wundheilung und Muskelerhalt bereit"),
      p(b("Fazit: "), "Der Körper braucht nach einer Operation in erster Linie Protein und essentielle sowie verzweigtkettige Aminosäuren (EAA & BCAA), um den Muskelabbau zu bremsen, die Wundheilung zu unterstützen und die Immunkompetenz aufrechtzuerhalten."),
      h3("Der Insulin-Vorteil von Protein"),
      p("Im Gegensatz zu Kohlenhydraten ist die Insulinantwort auf Proteinzufuhr nicht durch die postoperative Insulinresistenz beeinträchtigt. Protein erhöht die Aminosäurekonzentration im Blut, was direkt die Muskelproteinsynthese anregt, unabhängig davon, ob eine Insulinresistenz besteht. Deshalb ist Protein das entscheidende Makronährstoffziel rund um eine Operation."),
      h2("Zeitplan mit Mengenangaben"),
      warning("Alle Angaben sind allgemeine Orientierungswerte. Individuelle Anpassung durch Arzt oder Ernährungsberater ist zwingend erforderlich, besonders bei Diabetes, Nierenerkrankungen oder Mangelernährung."),
      h3("Vor der Operation"),
      table(["Zeitfenster", "Was essen / trinken?", "Menge (Orientierung)"], [
        ["7–10 Tage vorher", "Komplexe Kohlenhydrate (Vollkorn, Gemüse, Obst) + hochwertige Proteinquellen (Fleisch, Fisch, Eier, Milchprodukte)", "KH: ~60 % der Energie oder 8 g/kg/Tag; Protein: 1,2–2,0 g/kg/Tag"],
        ["Täglich verteilt", "Protein auf 4–5 Mahlzeiten verteilen", "20–40 g Protein pro Mahlzeit"],
        ["12 h vor OP", "Letzte vollständige Mahlzeit (abends): komplex, leicht verdaulich", "KH + Protein, normal portioniert"],
        ["Bis 6 h vor OP", "Keine festen Speisen mehr", "Trinknahrung, Proteinshake, Kakao, Sportgetränk erlaubt"],
        ["2 h vor OP", "Kohlenhydratlösung (nur auf ärztliche Anweisung)", "ca. 50 g Kohlenhydrate"],
        ["2 h vor OP", "Freie Aminosäuren / EAA-Supplement (nur auf Anweisung)", "individuelle Dosierung nach Produkt"],
      ]),
      h3("Nach der Operation"),
      table(["Zeitfenster", "Was essen / trinken?", "Menge (Orientierung)"], [
        ["So früh wie möglich", "Freie EAA & BCAA oder Protein-Getränk (geringer Mageninhalt)", "EAA & BCAA: individuelle Dosierung; Proteinshake ≥ 20 g"],
        ["Innerhalb 24 h", "Schrittweise zu fester Kost übergehen", "Proteinreich, gut verträgliche Kost"],
        ["Reha-Phase (täglich)", "Hochproteindiät, über den Tag verteilt", "1,6–2,0 g/kg/Tag (bis 3,0 g/kg/Tag möglich)"],
        ["3–4 h vor Therapie", "Kleine Mahlzeit aus KH + Protein", "50–100 g KH + 30–40 g Protein"],
        ["15–45 min vor Therapie", "KH- & Protein-haltiges Getränk", "Proteinshake mit KH-Anteil"],
        ["Nach Therapiesession", "Protein-Getränk oder proteinreiche Mahlzeit", "≥ 20–30 g Protein"],
      ]),
      h3("Weitere hilfreiche Supplemente in der Reha"),
      warning("Redaktionshinweis (vor Veröffentlichung entfernen): Health Claims prüfen."),
      ul(
        [b("Kreatin-Monohydrat: "), "Unterstützt Muskelkraft und Muskelmasse"],
        [b("HMB (β-Hydroxy-β-Methylbutyrat): "), "Hemmt Muskelproteinabbau"],
        [b("Omega-3-Fettsäuren: "), "Entzündungsmodulation, Unterstützung der Muskelproteinsynthese"],
        [b("Probiotika: "), "Unterstützung des Mikrobioms und der Nährstoffabsorption"],
      ),
      summary("Rund um eine Operation ist ausreichend Protein (inkl. EAA/BCAA) entscheidend, um den Muskelabbau zu bremsen, die Wundheilung zu unterstützen und die Immunkompetenz aufrechtzuerhalten. Orientieren Sie sich an den Zeitfenstern und Mengenangaben in den beiden Tabellen und passen Sie diese in Absprache mit Arzt oder Ernährungsberater individuell an."),
      p(i("Quelle: Hirsch KR, Wolfe RR, Ferrando AA. Pre- and Post-Surgical Nutrition for Preservation of Muscle Mass, Strength, and Functionality Following Orthopedic Surgery. Nutrients 2021; 13(5):1675.")),
    ),
  },
  {
    slug: "bewegung",
    title: "Säule der Bewegung",
    category: "bewegung",
    position: 0,
    body: doc(
      p("Gezielte, angepasste Bewegung ist ein zentraler Bestandteil jeder Rehabilitation. Kontrollierte mechanische Belastung regt die Durchblutung des betroffenen Gewebes an, fördert den Abtransport von Entzündungsstoffen und unterstützt den geordneten Aufbau von neuem Kollagen entlang der physiologischen Belastungslinien. Die Wundheilung verläuft dadurch schneller und das neue Gewebe wird belastbarer."),
      p("Über die lokale Wundheilung hinaus wirkt sich regelmäßige Bewegung positiv auf den gesamten Organismus aus: Sie erhält Muskelmasse und Kraft, verbessert die Beweglichkeit angrenzender Gelenke, unterstützt das Herz-Kreislauf-System und wirkt sich nachweislich positiv auf Stimmung und Schlafqualität aus. Ein strukturierter, schrittweise gesteigerter Trainingsplan ist daher die Grundlage für einen sicheren und nachhaltigen Return to Sport."),
      h3("Hinweise zu den Trainingsplänen"),
      p("Die Trainingspläne sind als Wochenpläne angelegt. Übungen und Parameter (Sätze, Wiederholungen, Gewicht, Pausen) sind bewusst nicht starr, sondern werden von Woche zu Woche an den aktuellen Zustand angepasst. Grundlage sind die aktuelle Wundheilungsphase, die individuelle Gewebebelastbarkeit und die Angaben im Schmerztagebuch. Nur wenn Belastung, Heilungsfortschritt und Schmerzniveau zusammenpassen, kann die nächste KRS-Stufe sicher erreicht werden."),
    ),
  },
  {
    slug: "schmerzampel",
    title: "Schmerztagebuch und Schmerzampel",
    category: "schmerz",
    position: 0,
    body: doc(
      p("Zur Selbsteinschätzung während des Trainings: Pain-Monitoring-Modell und Schmerzampel."),
      h3("Was ist die Schmerzampel?"),
      p("Die Schmerzampel ist ein einfaches Ampelsystem (grün, gelb, rot), mit dem Sie selbst einschätzen können, ob Ihr Schmerz während einer Übung noch im sicheren Bereich liegt. Sie wird häufig bei Sehnen- und Gelenkbeschwerden eingesetzt, damit Bewegung nicht komplett vermieden, aber auch keine Überlastung riskiert wird. Grundlage ist die Numerische Schmerzskala (NPRS) von 0 (kein Schmerz) bis 10 (stärkster vorstellbarer Schmerz)."),
      p("Entscheidend ist dabei nicht nur, wie stark der Schmerz während der Übung ist, sondern auch, ob er bis zum nächsten Morgen wieder auf Ihr Ausgangsniveau zurückgeht. Steigt der Schmerz in Ruhe dauerhaft an oder bleibt er über mehrere Tage erhöht, war die Belastung zu hoch und sollte reduziert werden."),
      baustein("ampel"),
      h3("Umgang mit Schmerzen während der Übung"),
      ul(
        "Leichte bis moderate Schmerzen während der Übung sind meist unbedenklich und kein Zeichen einer Schädigung; sie zeigen lediglich an, dass das Gewebe gerade belastet wird.",
        "Verändern Sie bei Bedarf lieber die Dosierung (Wiederholungen, Gewicht, Tempo, Bewegungsausmaß), als die Übung komplett zu meiden.",
        "Schmerz, der erst nach der Übung auftritt oder sich am nächsten Tag verschlechtert, zählt genauso wie Schmerz während der Übung: beides im Tagebuch dokumentieren.",
        "Bei anhaltenden Beschwerden im roten Bereich, plötzlich stark zunehmendem Schmerz, Schwellung oder Instabilitätsgefühl: Rücksprache mit Ihrer Physiotherapeutin / Ihrem Physiotherapeuten halten, statt eigenständig weiter zu trainieren.",
      ),
      h3("So wird eingetragen"),
      p("Tragen Sie nach jeder Trainingseinheit Ihren Schmerzwert auf der Numerischen Schmerzskala ein: 0 = kein Schmerz, 10 = stärkster vorstellbarer Schmerz. Prüfen Sie zusätzlich am nächsten Morgen, ob der Schmerz wieder auf das Ausgangsniveau zurückgegangen ist."),
      summary("Leichte bis moderate Schmerzen während des Trainings sind normal und kein Alarmsignal. Entscheidend ist die Schmerzampel als Richtwert sowie die Kontrolle am nächsten Morgen. Bleibt der Schmerz erhöht oder liegt wiederholt im roten Bereich, wird die Belastung reduziert und mit der Therapeutin bzw. dem Therapeuten besprochen."),
    ),
  },
  {
    slug: "reha-stadien",
    title: "Rehabilitationsstadien nach Verletzung oder Operation",
    category: "reha",
    position: 0,
    body: doc(
      p("Wundheilung, Gewebebelastbarkeit und Kraftaufbau (KRS-System). Nach einer Verletzung oder Operation muss der Aufbau von Gewebe und Kraft zum natürlichen Heilungsverlauf des Körpers passen. Wird zu früh oder zu stark belastet, kann das Gewebe erneut gereizt werden. Wird zu vorsichtig oder zu lange geschont, bildet sich schwächeres Gewebe."),
      h3("Was ist das KRS-System?"),
      p("Das KRS (Kraft-Rehabilitations-System, Bant et al., 2017) ist ein Stufenmodell für den Kraftaufbau in der Reha. Es unterteilt das Training in 9 aufeinander aufbauende Stufen, von Koordination über Kraftausdauer bis hin zu Maximalkraft, Schnellkraft und Sprungkraft (Plyometrie). Jede Stufe hat eigene Vorgaben für Serien, Wiederholungen und Pausen."),
      p("Ziel des KRS ist eine sichere, aber zügige Steigerung der Belastung: Der Wechsel zur nächsten Stufe richtet sich nicht nach einem festen Zeitplan, sondern danach, ob bestimmte Kriterien erfüllt sind, zum Beispiel ein schmerzfreier Bewegungsablauf oder eine ausreichende Kraft. So wird jede Person entsprechend ihrem eigenen Heilungsfortschritt trainiert. Auf welcher Stufe Sie gerade sind, legt Ihre Praxis fest; Sie sehen sie in Ihrem Profil."),
      baustein("krs"),
      h3("Was passiert bei der Wundheilung?"),
      p("Wundheilung ist der Prozess, mit dem der Körper verletztes Gewebe repariert, egal ob nach einer Verletzung oder einer Operation. Dieser Prozess läuft in mehreren aufeinanderfolgenden Phasen ab, die jeweils eigene biologische Aufgaben haben: die Entzündungsphase, die Proliferationsphase und die Konsolidierungs- bzw. Remodellierungsphase. Diese Phasen gehen fließend ineinander über und können sich zeitlich überschneiden. Jede Phase muss richtig ablaufen können, damit die nächste gut gelingt. Deshalb sollte auch die passende Belastung immer zur aktuellen Phase passen."),
      h3("1. Entzündungsphase (Tag 0–5)"),
      p("Direkt nach der Verletzung oder OP verengen sich die Blutgefäße und das Blut gerinnt, damit die Wunde nicht weiter blutet (Tag 0–2). Danach beginnt die eigentliche Entzündungsreaktion (Tag 2–5): Körpereigene Zellen räumen beschädigtes Gewebe ab. Dabei treten die typischen Entzündungszeichen auf: Schmerz, Schwellung, Rötung und Überwärmung. Diese Reaktion ist wichtig und sollte nicht unterdrückt werden."),
      info("Gewebebelastbarkeit: stark eingeschränkt (ca. 20–30 %)."),
      ul("Bewegung nur im schmerzfreien Bereich; der Schmerz zeigt die Grenze an", "Keine forcierte Mobilisation und keine Kraftbelastung", "Entzündungshemmende Medikamente (z. B. Ibuprofen, Diclofenac) können die Entzündungsreaktion abschwächen und dadurch die Heilung verzögern, da sie in den natürlichen Ablauf der Entzündung eingreifen", "Ziel: Schwellung und Schmerz reduzieren, Restfunktion der umliegenden Gelenke erhalten"),
      h3("2. Proliferationsphase (Tag 5–21, bis ca. Tag 28)"),
      p("Die Entzündungszeichen klingen langsam ab. Der Körper beginnt, neues Gewebe aufzubauen: Er bildet zunächst Kollagen Typ III, ein noch dünnes und wenig belastbares Ersatzgewebe. Wie gut dieses neue Gewebe am Ende wird, hängt davon ab, ob es in dieser Zeit passend belastet wird: zu wenig Reiz bremst den Aufbau, zu viel Reiz überlastet das noch empfindliche Gewebe."),
      info("Gewebebelastbarkeit: weiterhin gering; der Schmerz zeigt die Belastungsgrenze an."),
      ul("Aktive und unterstützte Bewegung, ohne das neue Gewebe zu überlasten", "Beginn von Koordinationstraining (KRS 1) und leichtem Kraftausdauertraining (KRS 2–3)", "Training mit vielen Wiederholungen, geringer Intensität und kurzen Pausen, im schmerzfreien Bereich", "Keine anstrengenden, schnellen oder sprunghaften Belastungen (noch kein intensives Krafttraining, keine Plyometrie)", "Die Entzündung sollte nicht erneut angestoßen werden: Hält der Schmerz länger als 24 Stunden nach der Belastung an, war der Reiz zu stark"),
      h3("3. Konsolidierungs- / Remodellierungsphase (ab ca. Tag 21 bis zu 12 Monate)"),
      p("Das anfängliche Kollagen Typ III wird nun je nach Gewebeart in stabileres Kollagen Typ I (z. B. in Sehnen, Bändern und Knochen) oder Kollagen Typ II (z. B. im Knorpel) umgewandelt. Das Gewebe richtet sich zunehmend nach der Art aus, wie es beansprucht wird; gezielte Belastungsreize sind in dieser Phase besonders wichtig für die spätere Gewebequalität."),
      info("Gewebebelastbarkeit: steigt schrittweise an (Start bei ca. 30 %, danach kontinuierlich zunehmend, teils mit vorübergehenden Schwankungen durch den Umbauprozess)."),
      ul("Schrittweise Steigerung der Belastung nach KRS 4 (extensives Rekrutieren) bis KRS 7 (intensives Rekrutieren)", "Übergang zu Training mit weniger Wiederholungen, höherem Gewicht und längeren Pausen (Maximalkraft)", "Aufbau von Schnellkraft, Vordehnung (Prestretch, KRS 8) und Sprungkraft (Plyometrie, KRS 9)", "Einbau von Bewegungsmustern aus Alltag und Sport, Überprüfung der Rückkehr-zum-Sport-Kriterien", "Unterschiedliche Gewebearten brauchen unterschiedlich lange zum Umbau; Bandgewebe kann zum Beispiel mehrere Jahre bis zur vollständigen Reifung benötigen"),
      h3("Zusammenspiel von Wundheilung und Kraftaufbau"),
      baustein("heilungskurve"),
      p("Zu jeder Wundheilungsphase passen bestimmte Maßnahmen, die die Heilung gezielt unterstützen:"),
      baustein("phasen"),
      summary("Bewegung muss in Art und Dosierung immer zur aktuellen Wundheilungsphase und Gewebebelastbarkeit passen. Die KRS-Stufen bieten dafür ein sicheres, kriteriengeleitetes Stufenmodell: Der Wechsel zur nächsten Stufe erfolgt nicht nach starrem Zeitplan, sondern nach Schmerzfreiheit, Beweglichkeit und Kraft."),
    ),
  },
];
